/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.milaifontanals;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.CharArrayReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.Reader;
import java.io.Writer;
import java.sql.Clob;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.JTable;

import p_interficiepersistencia.GestorBDExceptionTOT;

/**
 *
 * @author jordi
 */
public class Creacio_Actualitzar_Ruta extends javax.swing.JFrame {

    BDGeneral BD;
    JTable TableRuta;
    String usuString;
    /**
     * Creates new form Creacio_Actualitzar_Ruta
     */
    public Creacio_Actualitzar_Ruta() {
        initComponents();        
    }

    public Creacio_Actualitzar_Ruta(BDGeneral BD , String usu,JTable TableRuta){
        this.BD = BD;
        this.TableRuta = TableRuta;
        this.usuString = usu;
        initComponents();
        setLocationRelativeTo(null);
    }

    Ruta RutaDelUsuari;
    
    public Creacio_Actualitzar_Ruta(Ruta ruta,BDGeneral BD ,JTable TableRuta) {
        this.BD = BD;
        this.TableRuta = TableRuta;
        this.RutaDelUsuari = ruta;
        initComponents();
        setLocationRelativeTo(null);
        OmpleInfoUsuariDelaRuta(ruta);
    }

    private void OmpleInfoUsuariDelaRuta(Ruta ruta){

        System.out.println(ruta.toString());

        CATitol.setText(ruta.getTitol());
        CADescripcio.setText(ruta.getDescripcio());
        try {
            CAText.setText(clobToString(ruta.getText()));
        } catch (Exception e) {
            System.out.println("F al passar de Clob a string");
        }
        CADNegatiu.setText(String.valueOf(ruta.getDesnivellNegatiu()));
        CADPositiu.setText(String.valueOf(ruta.getDesnivellPositiu()));
        CADistancia.setText(String.valueOf(ruta.getDistancia()));
        CADifucultat.setSelectedIndex(ruta.getDificultat()-1);
        CATemps.setText(String.valueOf(ruta.getTemps()));



    }

    private static String clobToString(Clob clob) throws SQLException, IOException {
        if (clob == null) {
            return null;
        }
        StringBuilder sb = new StringBuilder();
        InputStream inStream = clob.getAsciiStream();
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream));
        String line;
        while ((line = reader.readLine()) != null) {
            sb.append(line);
        }
        reader.close();
        inStream.close();
        return sb.toString();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CATitol = new javax.swing.JTextField();
        CADescripcio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CAText = new javax.swing.JTextArea();
        CADistancia = new javax.swing.JTextField();
        CATemps = new javax.swing.JTextField();
        CADPositiu = new javax.swing.JTextField();
        CADNegatiu = new javax.swing.JTextField();
        CADifucultat = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnActualitzar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Titol:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Descripcio:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Text:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Distancia:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Temps:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Desnivell Positu:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Desnivell Negatiu:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Dificultat:");

        CATitol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CATitolKeyReleased(evt);
            }
        });

        CADescripcio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CADescripcioKeyReleased(evt);
            }
        });

        CAText.setColumns(20);
        CAText.setRows(5);
        CAText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CATextKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(CAText);

        CADistancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CADistanciaKeyReleased(evt);
            }
        });

        CATemps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CATempsKeyReleased(evt);
            }
        });

        CADPositiu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CADPositiuKeyReleased(evt);
            }
        });

        CADNegatiu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CADNegatiuKeyReleased(evt);
            }
        });

        CADifucultat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        btnCancelar.setText("Cancelar");

        btnActualitzar.setText("Actualitzar");
        btnActualitzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualitzarActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(CADifucultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CADistancia)
                    .addComponent(CATemps)
                    .addComponent(CADPositiu)
                    .addComponent(CADNegatiu)
                    .addComponent(CADescripcio)
                    .addComponent(CATitol))
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnActualitzar)
                    .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CATitol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CADescripcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CADistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CATemps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualitzar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CADPositiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CADNegatiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CADifucultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean Ftitol = true;
    private boolean FDescripcio = true;
    private boolean FText = true;
    private boolean FDistancia = true;
    private boolean FTemps = true;
    private boolean FDpositiu = true;
    private boolean FDnagatiu = true;

    boolean isInteger(String text) {
        try {
            Integer.parseInt(text);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private void CADNegatiuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CADNegatiuKeyReleased

        FDnagatiu = isInteger(CADNegatiu.getText());
        if(!FDnagatiu)
            CADNegatiu.setBackground(Color.RED);
        else
            CADNegatiu.setBackground(Color.white);
        
    }//GEN-LAST:event_CADNegatiuKeyReleased

    private void CADPositiuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CADPositiuKeyReleased


        FDpositiu = isInteger(CADPositiu.getText());
        if(!FDpositiu)
            CADPositiu.setBackground(Color.RED);
        else
            CADPositiu.setBackground(Color.white);

    }//GEN-LAST:event_CADPositiuKeyReleased

    private void CATempsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CATempsKeyReleased

        FTemps = isInteger(CATemps.getText());
        if(!FTemps)
            CATemps.setBackground(Color.RED);
        else
            CATemps.setBackground(Color.white);


    }//GEN-LAST:event_CATempsKeyReleased

    private void CADistanciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CADistanciaKeyReleased

        FDistancia = isInteger(CADistancia.getText());
        if(!FDistancia)
            CADistancia.setBackground(Color.RED);
        else
            CADistancia.setBackground(Color.white);
    }//GEN-LAST:event_CADistanciaKeyReleased

    private void CATitolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CATitolKeyReleased
        Ftitol = CATitol.getText().length() > 0;
        if(!Ftitol)
            CATitol.setBackground(Color.RED);
        else
            CATitol.setBackground(Color.white);

    }//GEN-LAST:event_CATitolKeyReleased

    private void CATextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CATextKeyReleased
        FText = CAText.getText().length() > 0;
        if(!FText)
            CAText.setBackground(Color.RED);
        else
            CAText.setBackground(Color.white);

    }//GEN-LAST:event_CATextKeyReleased

    private void CADescripcioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CADescripcioKeyReleased

        FDescripcio = CADescripcio.getText().length() > 0;
        if(!FDescripcio)
            CADescripcio.setBackground(Color.RED);
        else
            CADescripcio.setBackground(Color.white);    

    }//GEN-LAST:event_CADescripcioKeyReleased

    private static Clob stringToClob(String data) throws SQLException, IOException {
        char[] charData = data.toCharArray();
        CharArrayReader charArrayReader = new CharArrayReader(charData);

        return new Clob() {
            @Override
            public long length() throws SQLException {
                return charData.length;
            }

            @Override
            public String getSubString(long pos, int length) throws SQLException {
                return new String(charData, (int) pos - 1, length);
            }

            @Override
            public Reader getCharacterStream() throws SQLException {
                return charArrayReader;
            }

            // Implementar otros métodos de la interfaz Clob según sea necesario
            // ...

            @Override
            public void free() throws SQLException {
                // Liberar recursos si es necesario
                try {
                    charArrayReader.close();
                } catch (Exception e) {
                    throw new SQLException("Error al cerrar CharArrayReader", e);
                }
            }

            @Override
            public InputStream getAsciiStream() throws SQLException {
                throw new UnsupportedOperationException("Unimplemented method 'getAsciiStream'");
            }

            @Override
            public long position(String searchstr, long start) throws SQLException {
                throw new UnsupportedOperationException("Unimplemented method 'position'");
            }

            @Override
            public long position(Clob searchstr, long start) throws SQLException {
                throw new UnsupportedOperationException("Unimplemented method 'position'");
            }

            @Override
            public int setString(long pos, String str) throws SQLException {
                throw new UnsupportedOperationException("Unimplemented method 'setString'");
            }

            @Override
            public int setString(long pos, String str, int offset, int len) throws SQLException {
                throw new UnsupportedOperationException("Unimplemented method 'setString'");
            }

            @Override
            public OutputStream setAsciiStream(long pos) throws SQLException {
                throw new UnsupportedOperationException("Unimplemented method 'setAsciiStream'");
            }

            @Override
            public Writer setCharacterStream(long pos) throws SQLException {
                throw new UnsupportedOperationException("Unimplemented method 'setCharacterStream'");
            }

            @Override
            public void truncate(long len) throws SQLException {
                throw new UnsupportedOperationException("Unimplemented method 'truncate'");
            }

            @Override
            public Reader getCharacterStream(long pos, long length) throws SQLException {
                throw new UnsupportedOperationException("Unimplemented method 'getCharacterStream'");
            }
        };
    }
    

    private void btnActualitzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualitzarActionPerformed

        if(Ftitol && FDescripcio && FText && FDistancia && FTemps && FDpositiu && FDnagatiu){

            Ruta ruta = new Ruta();
            try {
                ruta.setId_Ruta(RutaDelUsuari.getId_Ruta());
                ruta.setTitol(CATitol.getText());
                ruta.setDescripcio(CADescripcio.getText());
                try {
                    ruta.setText(stringToClob(CAText.getText()));
                } catch (SQLException | IOException e) {
                    e.printStackTrace();
                }
                ruta.setDistancia(Integer.parseInt(CADistancia.getText()));
                ruta.setTemps(Integer.parseInt(CATemps.getText()));
                ruta.setDesnivellPositiu(Integer.parseInt(CADPositiu.getText()));
                ruta.setDesnivellNegatiu(Integer.parseInt(CADNegatiu.getText()));
                ruta.setDificultat(Integer.parseInt(CADifucultat.getSelectedItem().toString()));
                System.out.println(ruta.toString());
                boolean fet = BD.modificarRuta(ruta,CAText.getText());
                if(fet){
                    BD.validarCanvis();
                    JOptionPane.showMessageDialog(null, "Ruta Actualitzada", "Info", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    RutesUsuari.OmpleInfoUsuari(RutaDelUsuari.getUsuari());
                    //TableRuta.setModel(BD.getRutesDelUsuari(RutaDelUsuari.getUsuari()));
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error al Actualitzar la ruta", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException | ExceptionTOT e) {
                System.out.println("F al Actualtzar la ruta");
            } catch (GestorBDExceptionTOT e) {
                e.printStackTrace();
                System.out.println("Error al Actualitzar ruta BD");
            }    
        }
        else{
            JOptionPane.showMessageDialog(null, "Falten camps per omplir", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualitzarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        if(Ftitol && FDescripcio && FText && FDistancia && FTemps && FDpositiu && FDnagatiu){
            
            Ruta ruta = new Ruta();

                try {
                    //ruta.setId_Ruta(RutaDelUsuari.getId_Ruta());
                    ruta.setTitol(CATitol.getText());
                    ruta.setUsuari(usuString);
                    ruta.setDescripcio(CADescripcio.getText());
                    try {
                        ruta.setText(stringToClob(CAText.getText()));
                    } catch (SQLException | IOException e) {
                        e.printStackTrace();
                    }
                    ruta.setDistancia(Integer.parseInt(CADistancia.getText()));
                    ruta.setTemps(Integer.parseInt(CATemps.getText()));
                    ruta.setDesnivellPositiu(Integer.parseInt(CADPositiu.getText()));
                    ruta.setDesnivellNegatiu(Integer.parseInt(CADNegatiu.getText()));
                    ruta.setDificultat(Integer.parseInt(CADifucultat.getSelectedItem().toString()));
                    boolean fet = BD.afagirRuta(ruta, CAText.getText());
                    if(fet){
                        BD.validarCanvis();
                        JOptionPane.showMessageDialog(null, "Ruta Creada", "Info", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                        RutesUsuari.OmpleInfoUsuari(usuString);
                        //TableRuta.setModel(BD.getRutesDelUsuari(RutaDelUsuari.getUsuari()));
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Error al Crea la ruta", "Error", JOptionPane.ERROR_MESSAGE);
                    }


                } catch (NumberFormatException | ExceptionTOT e) {
                    e.printStackTrace();
                    System.out.println("Error Creacio ruta");
                } catch (GestorBDExceptionTOT e) {
                    e.printStackTrace();
                }            

        }




    }//GEN-LAST:event_btnCrearActionPerformed






    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creacio_Actualitzar_Ruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creacio_Actualitzar_Ruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creacio_Actualitzar_Ruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creacio_Actualitzar_Ruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creacio_Actualitzar_Ruta().setVisible(true);
            }
        });
    }


    
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CADNegatiu;
    private javax.swing.JTextField CADPositiu;
    private javax.swing.JTextField CADescripcio;
    private javax.swing.JComboBox<String> CADifucultat;
    private javax.swing.JTextField CADistancia;
    private javax.swing.JTextField CATemps;
    private javax.swing.JTextArea CAText;
    private javax.swing.JTextField CATitol;
    public javax.swing.JButton btnActualitzar;
    private javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables




    




}
